/* app.js — Ne Derdi? Single Page Application (Cloudflare Pages version) */

(function () {
  "use strict";

  /* ─── API Base — Cloudflare Worker URL (set after deploy) ─── */
  const API_BASE = window.NEDERDI_API_BASE || "";
  const INTERPRET_API = API_BASE ? API_BASE + "/interpret" : "";
  const NEWS_API = API_BASE ? API_BASE + "/news" : "";

  const mainEl = document.getElementById("main");

  /* ─── i18n ─────────────────────────────────────────────── */
  var TR = {
    hero_title: "Ne Derdi?",
    hero_tagline: "Tarihin büyük düşünürleri bugün yaşasaydı, günümüz olayları hakkında ne derdi?",
    nav_news: "Haberler", nav_philosophers: "Filozoflar",
    ne_derdi: "ne derdi?", ask_others: "Diğer filozoflara sor", sponsored: "Sponsorlu",
    phil_page_title: "Filozoflar", phil_page_subtitle: "20 büyük düşünür ve dünyayı nasıl yorumladıkları",
    key_concepts: "Temel Kavramlar", framework: "Düşünce Çerçevesi",
    thinking: " düşünüyor...", ne_hissederdi: "ne hissederdi?", ask_other_psychologists: "Diğer psikologlara sor", psych_page_title: "Psikologlar", psych_page_subtitle: "20 öncü psikolog ve insan zihnini nasıl yorumladıkları", nav_psychologists: "Psikologlar", psych_thinking: " analiz ediyor...", ne_yazardi: "ne yazardı?", ask_other_historians: "Diğer tarihçilere sor", hist_page_title: "Tarihçiler", hist_page_subtitle: "20 öncü tarihçi ve tarihe nasıl baktıkları", nav_historians: "Tarihçiler", hist_thinking: " araştırıyor...", rate_limit: "Saatlik limit doldu. Biraz sonra tekrar deneyin.",
    load_fail: "Yorum yüklenemedi.", api_not_ready: "Yorumlar yakında aktif olacak.",
    api_not_configured: "Yorum API'si henüz yapılandırılmadı.",
    rate_limit_modal: "Saatlik yorum limitine ulaştınız. Lütfen daha sonra tekrar deneyin.",
    load_fail_modal: "Yorum yüklenemedi. Lütfen tekrar deneyin.",
    toggle_dark: "Karanlık moda geç", toggle_light: "Açık moda geç",
    open_menu: "Menüyü aç", close_modal: "Kapat", skip_content: "Ana içeriğe geç",
    disclaimer: "Bu sitedeki filozof, psikolog ve tarihçi yorumları, ilgili düşünürlerin tarihsel eserleri ve düşünce yapıları temel alınarak yapay zekâ tarafından üretilmiştir. Yorumlar tamamen kurgusal olup gerçek kişilerin görüşlerini yansıtmaz, hiçbir kişi veya kurumu bağlamaz.",
    cat: { "Savaş": "Savaş", "Ekonomi": "Ekonomi", "Teknoloji": "Teknoloji", "Çevre": "Çevre", "Siyaset": "Siyaset", "Sağlık": "Sağlık", "Bilim": "Bilim", "Magazin": "Magazin", "Gündem": "Gündem", "Reklam": "Reklam", "Toplum": "Toplum" },
    months: ["Ocak","Şubat","Mart","Nisan","Mayıs","Haziran","Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık"]
  };
  var EN = {
    hero_title: "Ne Derdi? (What Would They Say?)",
    hero_tagline: "If history's greatest thinkers were alive today, what would they say about current events?",
    nav_news: "News", nav_philosophers: "Philosophers",
    ne_derdi: "what would they say?", ask_others: "Ask other philosophers", sponsored: "Sponsored",
    phil_page_title: "Philosophers", phil_page_subtitle: "20 great thinkers and how they interpreted the world",
    key_concepts: "Key Concepts", framework: "Philosophical Framework",
    thinking: " is thinking...", ne_hissederdi: "what would they feel?", ask_other_psychologists: "Ask other psychologists", psych_page_title: "Psychologists", psych_page_subtitle: "20 pioneering psychologists and how they interpreted the human mind", nav_psychologists: "Psychologists", psych_thinking: " is analyzing...", ne_yazardi: "what would they write?", ask_other_historians: "Ask other historians", hist_page_title: "Historians", hist_page_subtitle: "20 pioneering historians and how they interpreted history", nav_historians: "Historians", hist_thinking: " is researching...", rate_limit: "Hourly limit reached. Please try again later.",
    load_fail: "Could not load commentary.", api_not_ready: "Commentary coming soon.",
    api_not_configured: "Commentary API not configured yet.",
    rate_limit_modal: "You've reached the hourly commentary limit. Please try again later.",
    load_fail_modal: "Could not load commentary. Please try again.",
    toggle_dark: "Switch to dark mode", toggle_light: "Switch to light mode",
    open_menu: "Open menu", close_modal: "Close", skip_content: "Skip to content",
    disclaimer: "The philosopher, psychologist and historian commentaries on this site are generated by artificial intelligence based on the historical works and thought systems of the respective thinkers. All commentary is entirely fictional, does not reflect the actual views of real individuals, and is not binding on any person or institution.",
    cat: { "Savaş": "War", "Ekonomi": "Economy", "Teknoloji": "Technology", "Çevre": "Environment", "Siyaset": "Politics", "Sağlık": "Health", "Bilim": "Science", "Magazin": "Entertainment", "Gündem": "Headlines", "Reklam": "Ad", "Toplum": "Society" },
    months: ["January","February","March","April","May","June","July","August","September","October","November","December"]
  };
  var ZH = {
    hero_title: "他们会怎么说？",
    hero_tagline: "如果历史上最伟大的思想家活在今天，他们会如何评论当下的时事？",
    nav_news: "新闻", nav_philosophers: "哲学家",
    ne_derdi: "会怎么说？", ask_others: "问问其他哲学家", sponsored: "赞助",
    phil_page_title: "哲学家", phil_page_subtitle: "20位伟大的思想家及其世界观",
    key_concepts: "核心概念", framework: "思想框架",
    thinking: " 正在思考...", ne_hissederdi: "会有何感受？", ask_other_psychologists: "问问其他心理学家", psych_page_title: "心理学家", psych_page_subtitle: "20位先驱心理学家及其对人类心灵的解读", nav_psychologists: "心理学家", psych_thinking: " 正在分析...", ne_yazardi: "会写什么？", ask_other_historians: "问问其他历史学家", hist_page_title: "历史学家", hist_page_subtitle: "20位先驱历史学家及其历史观", nav_historians: "历史学家", hist_thinking: " 正在研究...", rate_limit: "每小时请求次数已达上限，请稍后再试。",
    load_fail: "评论加载失败。", api_not_ready: "评论功能即将上线。",
    api_not_configured: "评论API尚未配置。",
    rate_limit_modal: "您已达到每小时评论上限，请稍后再试。",
    load_fail_modal: "评论加载失败，请重试。",
    toggle_dark: "切换至深色模式", toggle_light: "切换至浅色模式",
    open_menu: "打开菜单", close_modal: "关闭", skip_content: "跳至主要内容",
    disclaimer: "本网站上的哲学家、心理学家和历史学家评论均由人工智能根据相关思想家的历史著作和思想体系生成。所有评论均为虚构内容，不代表任何真实人物的观点，对任何个人或机构不具约束力。",
    cat: { "Savaş": "战争", "Ekonomi": "经济", "Teknoloji": "科技", "Çevre": "环境", "Siyaset": "政治", "Sağlık": "健康", "Bilim": "科学", "Magazin": "娱乐", "Gündem": "要闻", "Reklam": "广告", "Toplum": "社会" },
    months: ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"]
  };
  function t(key) { return (currentLang === "en" ? EN : currentLang === "zh" ? ZH : TR)[key] || key; }
  function tCat(cat) { return (currentLang === "en" ? EN : currentLang === "zh" ? ZH : TR).cat[cat] || cat; }
  function pName(p) { return currentLang === "en" ? p.name : p.name_tr; }

  /* ─── Embedded Data ────────────────────────────────────── */

  const NEWS_ITEMS = [
    {
      id: "news-1",
      title: "Trump, İran Enerji Tesislerine Saldırıyı 10 Gün Erteledi: Barış Görüşmeleri Sürüyor",
      title_en: "Trump Delays Iran Energy Strikes by 10 Days: Peace Talks Ongoing",
      title_zh: "特朗普将对伊朗能源设施的打击推迟10天：和平谈判持续进行",
      summary: "ABD Başkanı Trump, İran'ın enerji altyapısına yönelik askeri operasyonları 6 Nisan'a kadar erteleyerek diplomatik çözüm arayışına süre tanıdı. Pakistan, Türkiye ve Mısır'ın arabuluculuk çabalarıyla ABD-İran arasındaki müzakereler devam ediyor. Trump, Hürmüz Boğazı'nın açılması için yeni bir ültimatom verirken, görüşmelerin 'olumlu ilerlediğini' savundu.",
      summary_en: "President Trump delayed military operations against Iran's energy infrastructure until April 6, giving diplomacy more time. Mediation efforts by Pakistan, Turkey and Egypt continue. Trump set a new ultimatum for reopening the Strait of Hormuz while claiming talks are 'progressing positively.'",
      summary_zh: "美国总统特朗普将针对伊朗能源基础设施的军事行动推迟至4月6日，为外交斡旋争取时间。巴基斯坦、土耳其和埃及的调解努力仍在继续。特朗普就重新开放霍尔木兹海峡发出新的最后通牒，同时声称谈判'进展积极'。",
      category: "Savaş",
      date: "2026-03-27",
      source_name: "Al Jazeera",
      source_url: "https://www.aljazeera.com/news/liveblog/2026/3/27/iran-war-live-trump-delays-attacks-on-iranian-energy-sector-by-10-days",
      philosopher_ids: ["hobbes","kant","hegel","arendt","ibn_khaldun","nietzsche","rousseau","gramsci"],
      featured_philosopher: "kant",
      psychologist_ids: ["fromm","frankl","milgram","zimbardo","jung","adler","horney","erikson"],
      featured_psychologist: "frankl",
      historian_ids: ["thucydides","hobsbawm","tuchman","zinn","toynbee","inalcik","said","gibbon"],
      featured_historian: "thucydides"
    },
    {
      id: "news-2",
      title: "G7 Dışişleri Bakanları Fransa'da Toplandı: İran ve Hürmüz Boğazı Gündeme Damgasını Vurdu",
      title_en: "G7 Foreign Ministers Meet in France: Iran and Strait of Hormuz Dominate Agenda",
      title_zh: "G7外长在法国会晤：伊朗和霍尔木兹海峡主导议程",
      summary: "G7 ülkelerinin dışişleri bakanları Paris yakınlarında iki günlük kritik zirvede bir araya geldi. ABD Dışişleri Bakanı Rubio, müttefiklerden İran savaşına destek istedi. Fransa, müzakere yoluyla çatışma çözümünü ve deniz ticaret yollarının yeniden açılmasını önceliklendirdi. Ukrayna, Gazze ve Sudan da gündemdeki konular arasında yer aldı.",
      summary_en: "G7 foreign ministers gathered near Paris for a two-day critical summit. US Secretary of State Rubio sought allied support for the Iran war. France prioritized conflict resolution through negotiation and reopening maritime trade routes. Ukraine, Gaza and Sudan were also on the agenda.",
      summary_zh: "G7外长在巴黎附近举行为期两天的关键峰会。美国国务卿鲁比奥寻求盟友对伊朗战争的支持。法国优先考虑通过谈判解决冲突并重新开放海上贸易航线。乌克兰、加沙和苏丹也在议程之列。",
      category: "Siyaset",
      date: "2026-03-27",
      source_name: "NPR",
      source_url: "https://www.npr.org/2026/03/27/nx-s1-5763475/iran-war-talks-rubio-markets-g7",
      philosopher_ids: ["plato","aristotle","hobbes","locke","rousseau","gramsci","arendt","confucius"],
      featured_philosopher: "arendt",
      psychologist_ids: ["milgram","zimbardo","fromm","erikson","adler","horney","bandura","lacan"],
      featured_psychologist: "milgram",
      historian_ids: ["thucydides","hobsbawm","zinn","said","wallerstein","carr","sima_qian","eco"],
      featured_historian: "hobsbawm"
    },
    {
      id: "news-3",
      title: "İran Savaşı Küresel Ekonomiyi Sarstı: Borsa Düştü, Petrol 120 Dolara Dayandı",
      title_en: "Iran War Shakes Global Economy: Stocks Fall, Oil Nears $120",
      title_zh: "伊朗战争撼动全球经济：股市下跌，油价逼近120美元",
      summary: "İran savaşının bir ayına yaklaşmasıyla Dow, NASDAQ ve S&P 500 endeksleri yüzde 5'ten fazla değer kaybetti. ABD'de benzin fiyatları galon başına yaklaşık 1 dolar arttı. Brent petrol 120 dolar seviyesine yaklaştı ve Macquarie, savaş hazirana kadar sürerse petrolün 200 dolara çıkabileceği uyarısında bulundu. Küresel enflasyon endişeleri artıyor.",
      summary_en: "As the Iran war approaches one month, the Dow, NASDAQ and S&P 500 have all fallen over 5%. US gas prices rose by $1 per gallon. Brent crude neared $120, and Macquarie warned oil could hit $200 if the war lasts until June. Global inflation fears are rising.",
      summary_zh: "随着伊朗战争进入第四周，道琼斯、纳斯达克和标普500指数均下跌超过5%。美国汽油价格每加仑上涨约1美元。布伦特原油逼近120美元，麦格理警告若战争持续至六月，油价可能飙升至200美元。全球通胀担忧加剧。",
      category: "Ekonomi",
      date: "2026-03-27",
      source_name: "TODAY",
      source_url: "https://www.today.com/video/us-economy-under-pressure-as-iran-war-impacts-stocks-oil-gas-260183109700",
      philosopher_ids: ["adam_smith","marx","hayek","ibn_khaldun","locke","hegel","al_farabi","aristotle"],
      featured_philosopher: "marx",
      psychologist_ids: ["fromm","maslow","skinner","bandura","adler","vygotsky","james","watson"],
      featured_psychologist: "fromm",
      historian_ids: ["wallerstein","eco","braudel","hobsbawm","galeano","thompson","inalcik","inalcik"],
      featured_historian: "wallerstein"
    },
    {
      id: "news-4",
      title: "İsrail, İran Devrim Muhafızları Deniz Kuvvetleri Komutanını Öldürdüğünü Açıkladı",
      title_en: "Israel Says It Killed Iran's Revolutionary Guard Naval Commander",
      title_zh: "以色列宣布击毙伊朗革命卫队海军司令",
      summary: "İsrail, Hürmüz Boğazı'nın kapatılmasından sorumlu tutulan İran Devrim Muhafızları Deniz Kuvvetleri Komutanı Ali Rıza Tangiri'nin Bender Abbas'ta düzenlenen bir hava saldırısında öldürüldüğünü duyurdu. İsrail ayrıca Tahran'da balistik füze üretim tesislerini ve hava savunma sistemlerini hedef aldı. İsrail Savunma Bakanı, olası ateşkes öncesi 48 saatlik yoğun saldırı emri verildiğini belirtti.",
      summary_en: "Israel announced the killing of Iran's IRGC Naval Commander Ali Reza Tangsiri in an airstrike in Bandar Abbas. He was held responsible for closing the Strait of Hormuz. Israel also targeted ballistic missile production facilities and air defense systems in Tehran. The Defense Minister ordered a 48-hour surge in attacks before a potential ceasefire.",
      summary_zh: "以色列宣布在阿巴斯港的空袭中击毙了伊朗革命卫队海军司令阿里·雷扎·坦格西里。他被认为是关闭霍尔木兹海峡的责任人。以色列还在德黑兰打击了弹道导弹生产设施和防空系统。国防部长下令在可能的停火前发起48小时密集攻击。",
      category: "Savaş",
      date: "2026-03-27",
      source_name: "The Times of Israel",
      source_url: "https://www.timesofisrael.com/liveblog-march-27-2026/",
      philosopher_ids: ["hobbes","kant","hegel","arendt","ibn_khaldun","nietzsche","rousseau","gramsci"],
      featured_philosopher: "nietzsche",
      psychologist_ids: ["fromm","frankl","milgram","zimbardo","jung","adler","horney","erikson"],
      featured_psychologist: "zimbardo",
      historian_ids: ["thucydides","hobsbawm","tuchman","zinn","toynbee","inalcik","said","gibbon"],
      featured_historian: "tuchman"
    },
    {
      id: "news-5",
      title: "ABD, Tomahawk Füzelerini Alarma Yol Açan Hızla Tüketiyor",
      title_en: "US Burning Through Tomahawk Missiles at Alarming Rate",
      title_zh: "美国以惊人速度消耗战斧导弹",
      summary: "ABD ordusu İran savaşında 7.800'den fazla hedefi vurdu ve 120'den fazla İran gemisini imha etti. Ancak Pentagon yetkilileri, Tomahawk seyir füzelerinin tüketim hızının endişe verici boyutlara ulaştığını bildirdi. 8.000'den fazla savaş uçuşu gerçekleştirilirken, cephane stokları üzerindeki baskı artıyor.",
      summary_en: "The US military has struck over 7,800 targets in Iran and destroyed 120+ Iranian vessels. However, Pentagon officials report that the rate of Tomahawk cruise missile consumption has reached alarming levels. With over 8,000 combat flights conducted, pressure on ammunition stockpiles is mounting.",
      summary_zh: "美军在伊朗战争中打击了超过7800个目标，摧毁了120余艘伊朗舰艇。然而五角大楼官员报告称，战斧巡航导弹的消耗速度已达到令人担忧的水平。在执行超过8000架次作战飞行的同时，弹药库存压力持续增大。",
      category: "Savaş",
      date: "2026-03-27",
      source_name: "CNN",
      source_url: "https://www.cnn.com/2026/03/27/world/live-news/iran-war-us-israel-trump",
      philosopher_ids: ["hobbes","kant","hegel","arendt","ibn_khaldun","nietzsche","rousseau","gramsci"],
      featured_philosopher: "hobbes",
      psychologist_ids: ["fromm","frankl","milgram","zimbardo","jung","adler","horney","erikson"],
      featured_psychologist: "milgram",
      historian_ids: ["thucydides","hobsbawm","tuchman","zinn","toynbee","inalcik","said","gibbon"],
      featured_historian: "zinn"
    },
    {
      id: "news-6",
      title: "Trump, İran Halkının Sokağa Çıkamadığını İtiraf Etti: Keskin Nişancılar Vuruyor",
      title_en: "Trump Admits Iranian People Are 'Petrified' of Taking to the Streets",
      title_zh: "特朗普承认伊朗民众'恐惧'上街抗议",
      summary: "ABD Başkanı Trump, Fox News'a verdiği röportajda İran halkının sokağa çıkamadığını kabul etti. 'Bir tarafin silahları var ve sizi vuruyorlar' dedi. Savaş öncesi rejim değişikliği umutlarından geri adım atan Trump, İran rejiminin dört haftalık savaşa rağmen ayakta kaldığını dolaylı olarak kabul etmiş oldu.",
      summary_en: "President Trump told Fox News that Iranian people are 'petrified' of protesting. 'One side has guns, and they shoot you,' he said. Stepping back from pre-war hopes of regime change, Trump implicitly acknowledged that the Iranian regime has weathered four weeks of war.",
      summary_zh: "美国总统特朗普在接受福克斯新闻采访时承认伊朗人民'恐惧'上街。他说：'一方有枪，他们会开枪打你。'从战前的政权更迭希望中退后一步，特朗普间接承认伊朗政权经受住了四周的战争考验。",
      category: "Siyaset",
      date: "2026-03-27",
      source_name: "The Times of Israel",
      source_url: "https://www.timesofisrael.com/liveblog-march-27-2026/",
      philosopher_ids: ["plato","aristotle","hobbes","locke","rousseau","gramsci","arendt","confucius"],
      featured_philosopher: "gramsci",
      psychologist_ids: ["milgram","zimbardo","fromm","erikson","adler","horney","bandura","lacan"],
      featured_psychologist: "fromm",
      historian_ids: ["thucydides","hobsbawm","zinn","said","wallerstein","carr","sima_qian","eco"],
      featured_historian: "zinn"
    },
    {
      id: "news-7",
      title: "Eski ABD Güvenlik Danışmanı Sullivan: İran Cenevre'de Anlaşma Önerdi, Müzakereciler Anlamadı",
      title_en: "Former US Adviser Sullivan: Iran Made a Proposal in Geneva, Negotiators Didn't Understand It",
      title_zh: "美前国安顾问沙利文：伊朗在日内瓦提出方案，谈判代表未能理解",
      summary: "Biden dönemi Ulusal Güvenlik Danışmanı Jake Sullivan, savaş öncesi Cenevre'deki son görüşmelerde İran'ın nükleer sorunu büyük ölçüde çözen bir teklif sunduğunu ancak ABD müzakerecilerinin bunu anlayamadığını açıkladı. Sullivan, Witkoff ve Kushner'ın tecrübesiz olduğunu ve askeri harekâta geçmekte acele edildiğini söyledi.",
      summary_en: "Former National Security Adviser Jake Sullivan revealed that Iran presented a proposal in Geneva that 'significantly addressed the nuclear issue' but US negotiators 'did not comprehend what was being offered.' Sullivan said Witkoff and Kushner were inexperienced and rushed to military action.",
      summary_zh: "前国家安全顾问杰克·沙利文透露，伊朗在日内瓦提出了一项'在很大程度上解决核问题'的方案，但美国谈判代表'未能理解所提供的内容'。沙利文表示维特科夫和库什纳缺乏经验，仓促走向军事行动。",
      category: "Gündem",
      date: "2026-03-27",
      source_name: "The New York Times",
      source_url: "https://www.nytimes.com/live/2026/03/27/world/iran-war-trump-oil-israel",
      philosopher_ids: ["plato","kant","hegel","nietzsche","marx","arendt","foucault","ibn_khaldun"],
      featured_philosopher: "foucault",
      psychologist_ids: ["freud","jung","fromm","erikson","milgram","zimbardo","frankl","maslow"],
      featured_psychologist: "jung",
      historian_ids: ["hobsbawm","toynbee","spengler","inalcik","carr","sima_qian","braudel","eco"],
      featured_historian: "toynbee"
    },
    {
      id: "news-8",
      title: "Körfez Ülkeleri Saldırı Altında: Kuveyt Limanına Drone, Bahreyn'de Alarm",
      title_en: "Gulf States Under Attack: Drone Hits Kuwait Port, Alarms in Bahrain",
      title_zh: "海湾国家遭袭：无人机袭击科威特港口，巴林拉响警报",
      summary: "İran Devrim Muhafızları, ABD üslerinin bulunduğu BAE, Bahreyn ve Kuveyt'e füze ve İHA saldırıları düzenledi. Kuveyt limanı İHA saldırısına uğrarken, Bahreyn'de sirenler çaldı ve Katar güvenlik seviyesini yükseltti. Hürmüz Boğazı'ndaki Taylandlı bir kargo gemisi İran'ın Kişm Adası açıklarında karaya oturdu.",
      summary_en: "Iran's Revolutionary Guards launched missile and drone attacks on UAE, Bahrain and Kuwait where US bases are located. Kuwait's port was hit by drones, sirens sounded in Bahrain and Qatar raised its security level. A Thai cargo ship in the Strait of Hormuz ran aground off Iran's Qeshm Island.",
      summary_zh: "伊朗革命卫队向设有美军基地的阿联酋、巴林和科威特发射导弹和无人机。科威特港口遭无人机袭击，巴林拉响警报，卡塔尔提升安全级别。一艘泰国货轮在霍尔木兹海峡伊朗格什姆岛附近搁浅。",
      category: "Savaş",
      date: "2026-03-27",
      source_name: "NPR",
      source_url: "https://www.npr.org/2026/03/27/nx-s1-5763475/iran-war-talks-rubio-markets-g7",
      philosopher_ids: ["hobbes","kant","hegel","arendt","ibn_khaldun","nietzsche","rousseau","gramsci"],
      featured_philosopher: "ibn_khaldun",
      psychologist_ids: ["fromm","frankl","milgram","zimbardo","jung","adler","horney","erikson"],
      featured_psychologist: "erikson",
      historian_ids: ["thucydides","hobsbawm","tuchman","zinn","toynbee","inalcik","said","gibbon"],
      featured_historian: "gibbon"
    },
    {
      id: "news-9",
      title: "Türkiye, Riyad Bildirisinde İran Saldırılarını Kınadı Ancak ABD-İsrail Saldırılarına Değinilmedi",
      title_en: "Turkey Signs Riyadh Statement Condemning Iran but No Mention of US-Israel Strikes",
      title_zh: "土耳其签署利雅得声明谴责伊朗，但未提及美以打击行动",
      summary: "Türkiye, 12 Arap ve İslam ülkesiyle birlikte Riyad'da imzalanan ortak bildiride İran'ın bölgesel saldırılarını kınadı. Ancak bildiri, ABD ve İsrail'in İran'a yönelik saldırılarından hiç söz etmedi. Türkiye ayrıca İncirlik Üssü'ne konuşlandırılan ek NATO Patriot sistemiyle güney sınırlarını güçlendirmeye devam ediyor.",
      summary_en: "Turkey joined 12 Arab and Muslim countries in signing a Riyadh statement condemning Iran's regional attacks. However, the statement made no mention of US and Israeli strikes on Iran. Turkey continues to strengthen its southern borders with an additional NATO Patriot system deployed to Incirlik Air Base.",
      summary_zh: "土耳其与12个阿拉伯和伊斯兰国家共同签署利雅得声明，谴责伊朗的地区攻击行为。然而声明只字未提美国和以色列对伊朗的打击。土耳其继续通过在因吉尔利克空军基地部署额外的北约爱国者系统加强南部边境防御。",
      category: "Gündem",
      date: "2026-03-27",
      source_name: "Anadolu Ajansı",
      source_url: "https://www.aa.com.tr/en/world/morning-briefing-march-19-2026/3870847",
      philosopher_ids: ["plato","kant","hegel","nietzsche","marx","arendt","foucault","ibn_khaldun"],
      featured_philosopher: "hegel",
      psychologist_ids: ["freud","jung","fromm","erikson","milgram","zimbardo","frankl","maslow"],
      featured_psychologist: "erikson",
      historian_ids: ["hobsbawm","toynbee","spengler","inalcik","carr","sima_qian","braudel","eco"],
      featured_historian: "carr"
    },
    {
      id: "news-10",
      title: "Mariah Carey 57 Yaşında: Pop Müziğin Kraliçesi Doğum Gününü Kutluyor",
      title_en: "Mariah Carey Turns 57: The Queen of Pop Celebrates Her Birthday",
      title_zh: "玛丽亚·凯莉57岁：流行天后庆祝生日",
      summary: "Dünya genelinde 200 milyondan fazla albüm satan ve Billboard Hot 100 listesinde 19 bir numaralı şarkıyla Beatles'tan sonra ikinci sırada yer alan Mariah Carey, 57. yaşını kutluyor. Beş oktavlık ses aralığıyla müzik tarihine damgasını vuran sanatçı, yeni albüm çalışmalarının devam ettiğini duyurdu.",
      summary_en: "Mariah Carey, who has sold over 200 million albums worldwide and holds 19 number-one singles on the Billboard Hot 100 — second only to The Beatles — celebrates her 57th birthday. The artist with a five-octave vocal range announced that work on her new album continues.",
      summary_zh: "全球唱片销量超过2亿张、在Billboard Hot 100榜上拥有19首冠军单曲（仅次于披头士）的玛丽亚·凯莉迎来57岁生日。这位拥有五个八度音域的艺术家宣布新专辑正在制作中。",
      category: "Magazin",
      date: "2026-03-27",
      source_name: "Parade",
      source_url: "https://parade.com/celebrities/famous-celebrity-birthdays-today-march-27-2026-mariah-carey-quentin-tarantino",
      philosopher_ids: ["nietzsche","kierkegaard","foucault","rousseau","plato","confucius","lao_tzu","aristotle"],
      featured_philosopher: "kierkegaard",
      psychologist_ids: ["freud","jung","lacan","horney","adler","klein","erikson","fromm"],
      featured_psychologist: "freud",
      historian_ids: ["herodotus","michelet","sima_qian","inalcik","gibbon","tuchman","said","spengler"],
      featured_historian: "herodotus"
    }
  ];

  const PHILOSOPHERS_LIST = [
    { id: "nietzsche", name: "Friedrich Nietzsche", name_tr: "Friedrich Nietzsche", years: "1844–1900", tradition: "Existentialism, Nihilism", key_concepts: "Will to Power, Übermensch, Eternal Recurrence, Master-Slave Morality" },
    { id: "marx", name: "Karl Marx", name_tr: "Karl Marx", years: "1818–1883", tradition: "Historical Materialism, Communism", key_concepts: "Class Struggle, Capital, Alienation, Base-Superstructure" },
    { id: "hegel", name: "G.W.F. Hegel", name_tr: "Georg Wilhelm Friedrich Hegel", years: "1770–1831", tradition: "German Idealism", key_concepts: "Dialectic, Absolute Spirit, History as Progress, Thesis-Antithesis-Synthesis" },
    { id: "ibn_khaldun", name: "Ibn Khaldun", name_tr: "İbn Haldun", years: "1332–1406", tradition: "Islamic Philosophy, Social Science", key_concepts: "Asabiyyah (Social Cohesion), Cyclical History, Umran (Civilization)" },
    { id: "plato", name: "Plato", name_tr: "Platon", years: "428–348 BC", tradition: "Classical Greek Philosophy", key_concepts: "Theory of Forms, Philosopher-King, The Republic, Allegory of the Cave" },
    { id: "aristotle", name: "Aristotle", name_tr: "Aristoteles", years: "384–322 BC", tradition: "Classical Greek Philosophy", key_concepts: "Golden Mean, Virtue Ethics, Telos, Political Animal" },
    { id: "kant", name: "Immanuel Kant", name_tr: "Immanuel Kant", years: "1724–1804", tradition: "German Idealism, Enlightenment", key_concepts: "Categorical Imperative, Duty, Perpetual Peace, Autonomy" },
    { id: "foucault", name: "Michel Foucault", name_tr: "Michel Foucault", years: "1926–1984", tradition: "Post-Structuralism", key_concepts: "Power/Knowledge, Discipline, Surveillance, Biopolitics" },
    { id: "rousseau", name: "Jean-Jacques Rousseau", name_tr: "Jean-Jacques Rousseau", years: "1712–1778", tradition: "Social Contract Theory", key_concepts: "Social Contract, General Will, Noble Savage, Natural Freedom" },
    { id: "hobbes", name: "Thomas Hobbes", name_tr: "Thomas Hobbes", years: "1588–1679", tradition: "Social Contract Theory, Political Realism", key_concepts: "Leviathan, State of Nature, Social Contract, Sovereign Authority" },
    { id: "locke", name: "John Locke", name_tr: "John Locke", years: "1632–1704", tradition: "Liberalism, Empiricism", key_concepts: "Natural Rights, Property, Consent of the Governed, Tabula Rasa" },
    { id: "kierkegaard", name: "Søren Kierkegaard", name_tr: "Søren Kierkegaard", years: "1813–1855", tradition: "Existentialism, Christian Philosophy", key_concepts: "Leap of Faith, Anxiety, Authenticity, Three Stages of Existence" },
    { id: "hayek", name: "Friedrich Hayek", name_tr: "Friedrich Hayek", years: "1899–1992", tradition: "Classical Liberalism, Austrian Economics", key_concepts: "Spontaneous Order, Road to Serfdom, Knowledge Problem, Free Markets" },
    { id: "adam_smith", name: "Adam Smith", name_tr: "Adam Smith", years: "1723–1790", tradition: "Classical Economics, Moral Philosophy", key_concepts: "Invisible Hand, Division of Labor, Moral Sentiments, Free Trade" },
    { id: "arendt", name: "Hannah Arendt", name_tr: "Hannah Arendt", years: "1906–1975", tradition: "Political Philosophy", key_concepts: "Banality of Evil, Public Sphere, Totalitarianism, Vita Activa" },
    { id: "gramsci", name: "Antonio Gramsci", name_tr: "Antonio Gramsci", years: "1891–1937", tradition: "Marxism, Cultural Theory", key_concepts: "Cultural Hegemony, Organic Intellectual, War of Position, Civil Society" },
    { id: "confucius", name: "Confucius", name_tr: "Konfüçyüs", years: "551–479 BC", tradition: "Confucianism", key_concepts: "Ren (Benevolence), Li (Ritual), Junzi (Gentleman), Filial Piety" },
    { id: "lao_tzu", name: "Lao Tzu", name_tr: "Lao Tzu", years: "~6th century BC", tradition: "Taoism", key_concepts: "Tao (The Way), Wu Wei (Non-Action), Yin-Yang, Simplicity" },
    { id: "avicenna", name: "Avicenna (Ibn Sina)", name_tr: "İbn Sina", years: "980–1037", tradition: "Islamic Philosophy, Neoplatonism", key_concepts: "Necessary Being, Flying Man, Soul-Body Unity, Scientific Method" },
    { id: "al_farabi", name: "Al-Farabi", name_tr: "Farabi", years: "872–950", tradition: "Islamic Philosophy, Political Philosophy", key_concepts: "Virtuous City, Philosopher-Prophet, Happiness, Classification of Sciences" }
  ];

  const PSYCHOLOGISTS_LIST = [
    { id: "wundt", name: "Wilhelm Wundt", name_tr: "Wilhelm Wundt", years: "1832–1920", tradition: "Experimental Psychology", key_concepts: "Introspection, Structuralism, Apperception, Voluntarism" },
    { id: "freud", name: "Sigmund Freud", name_tr: "Sigmund Freud", years: "1856–1939", tradition: "Psychoanalysis", key_concepts: "Unconscious Mind, Id-Ego-Superego, Dream Analysis, Oedipus Complex" },
    { id: "jung", name: "Carl Jung", name_tr: "Carl Jung", years: "1875–1961", tradition: "Analytical Psychology", key_concepts: "Collective Unconscious, Archetypes, Individuation, Shadow Self" },
    { id: "james", name: "William James", name_tr: "William James", years: "1842–1910", tradition: "Pragmatism, Functionalism", key_concepts: "Stream of Consciousness, Pragmatic Truth, Radical Empiricism, Will to Believe" },
    { id: "maslow", name: "Abraham Maslow", name_tr: "Abraham Maslow", years: "1908–1970", tradition: "Humanistic Psychology", key_concepts: "Hierarchy of Needs, Self-Actualization, Peak Experiences, Deficiency vs Growth" },
    { id: "rogers", name: "Carl Rogers", name_tr: "Carl Rogers", years: "1902–1987", tradition: "Humanistic Psychology", key_concepts: "Unconditional Positive Regard, Client-Centered Therapy, Self-Concept, Empathy" },
    { id: "lacan", name: "Jacques Lacan", name_tr: "Jacques Lacan", years: "1901–1981", tradition: "Psychoanalysis, Structuralism", key_concepts: "Mirror Stage, The Real-Symbolic-Imaginary, Desire of the Other, Jouissance" },
    { id: "piaget", name: "Jean Piaget", name_tr: "Jean Piaget", years: "1896–1980", tradition: "Developmental Psychology", key_concepts: "Cognitive Development Stages, Schema, Assimilation-Accommodation, Constructivism" },
    { id: "watson", name: "John B. Watson", name_tr: "John B. Watson", years: "1878–1958", tradition: "Behaviorism", key_concepts: "Classical Conditioning, Stimulus-Response, Little Albert, Environmental Determinism" },
    { id: "vygotsky", name: "Lev Vygotsky", name_tr: "Lev Vygotsky", years: "1896–1934", tradition: "Social Constructivism", key_concepts: "Zone of Proximal Development, Scaffolding, Social Learning, Inner Speech" },
    { id: "fromm", name: "Erich Fromm", name_tr: "Erich Fromm", years: "1900–1980", tradition: "Social Psychology, Neo-Freudianism", key_concepts: "Escape from Freedom, Having vs Being, Productive Character, Social Unconscious" },
    { id: "skinner", name: "B.F. Skinner", name_tr: "B.F. Skinner", years: "1904–1990", tradition: "Radical Behaviorism", key_concepts: "Operant Conditioning, Reinforcement, Skinner Box, Behavioral Engineering" },
    { id: "frankl", name: "Viktor Frankl", name_tr: "Viktor Frankl", years: "1905–1997", tradition: "Existential Psychology", key_concepts: "Logotherapy, Will to Meaning, Existential Vacuum, Tragic Optimism" },
    { id: "bandura", name: "Albert Bandura", name_tr: "Albert Bandura", years: "1925–2021", tradition: "Social Cognitive Theory", key_concepts: "Self-Efficacy, Observational Learning, Bobo Doll, Reciprocal Determinism" },
    { id: "erikson", name: "Erik Erikson", name_tr: "Erik Erikson", years: "1902–1994", tradition: "Developmental Psychology", key_concepts: "Eight Stages of Development, Identity Crisis, Psychosocial Development, Generativity" },
    { id: "horney", name: "Karen Horney", name_tr: "Karen Horney", years: "1885–1952", tradition: "Neo-Freudianism, Feminist Psychology", key_concepts: "Neurotic Needs, Womb Envy, Basic Anxiety, Idealized Self" },
    { id: "adler", name: "Alfred Adler", name_tr: "Alfred Adler", years: "1870–1937", tradition: "Individual Psychology", key_concepts: "Inferiority Complex, Striving for Superiority, Social Interest, Birth Order" },
    { id: "klein", name: "Melanie Klein", name_tr: "Melanie Klein", years: "1882–1960", tradition: "Object Relations Theory", key_concepts: "Paranoid-Schizoid Position, Depressive Position, Projective Identification, Play Therapy" },
    { id: "milgram", name: "Stanley Milgram", name_tr: "Stanley Milgram", years: "1933–1984", tradition: "Social Psychology", key_concepts: "Obedience to Authority, Milgram Experiment, Six Degrees of Separation, Conformity" },
    { id: "zimbardo", name: "Philip Zimbardo", name_tr: "Philip Zimbardo", years: "1933–", tradition: "Social Psychology", key_concepts: "Stanford Prison Experiment, Lucifer Effect, Time Perspective, Heroic Imagination" }
  ];

  const HISTORIANS_LIST = [
    { id: "herodotus", name: "Herodotus", name_tr: "Heredot", years: "M.Ö. 484–425", tradition: "Tarihin Babası", key_concepts: "Anlatısal tarih, kültürel karşılaştırma, saha araştırması, gelenek ve göreneklerin kaydı" },
    { id: "thucydides", name: "Thucydides", name_tr: "Tukididis", years: "M.Ö. 460–400", tradition: "Siyasi Tarih, Realizm", key_concepts: "Güç politikası, savaş analizi, kanıta dayalı tarih, Melos Diyaloğu" },
    { id: "braudel", name: "Fernand Braudel", name_tr: "Fernand Braudel", years: "1902–1985", tradition: "Annales Okulu, Uzun Süre", key_concepts: "Longue durée (uzun süre), coğrafyanın tarihe etkisi, üç zamanlı tarih, Akdeniz dünyası" },
    { id: "hobsbawm", name: "Eric Hobsbawm", name_tr: "Eric Hobsbawm", years: "1917–2012", tradition: "Marksist Tarihçilik", key_concepts: "Devrimler çağı, sanayi devrimi, icat edilmiş gelenekler, kısa 20. yüzyıl, aşırılıklar çağı" },
    { id: "inalcik", name: "Halil İnalcık", name_tr: "Halil İnalcık", years: "1916–2016", tradition: "Osmanlı Tarihçiliği", key_concepts: "Osmanlı ekonomik ve sosyal tarihi, tımar sistemi, devlet yapılanması, arşiv temelli araştırma" },
    { id: "toynbee", name: "Arnold Toynbee", name_tr: "Arnold Toynbee", years: "1889–1975", tradition: "Karşılaştırmalı Medeniyet Tarihi", key_concepts: "Meydan okuma-yanıt teorisi, medeniyetlerin doğuşu ve çöküşü, evrensel devlet, yaratıcı azınlık" },
    { id: "spengler", name: "Oswald Spengler", name_tr: "Oswald Spengler", years: "1880–1936", tradition: "Kültür Morfolojisi", key_concepts: "Batının çöküşü, kültürlerin organik döngüsü, Faustçu kültür, medeniyetlerin ömrü" },
    { id: "zinn", name: "Howard Zinn", name_tr: "Howard Zinn", years: "1922–2010", tradition: "Halkın Tarihi, Aktivist Tarihçilik", key_concepts: "Aşağıdan tarih, ezilenlerin perspektifi, Amerikan halk tarihi, sivil itaatsizlik" },
    { id: "said", name: "Edward Said", name_tr: "Edward Said", years: "1935–2003", tradition: "Postkolonyal Tarih", key_concepts: "Oryantalizm, Doğu-Batı ikiliği, kültürel emperyalizm, sürgün kimliği" },
    { id: "thompson", name: "E.P. Thompson", name_tr: "E.P. Thompson", years: "1924–1993", tradition: "Sosyal Tarih, İngiliz Marksizmi", key_concepts: "İngiliz işçi sınıfının oluşumu, ahlak ekonomisi, aşağıdan tarih, sınıf bilinci" },
    { id: "ranke", name: "Leopold von Ranke", name_tr: "Leopold von Ranke", years: "1795–1886", tradition: "Modern Tarih Bilimi", key_concepts: "Wie es eigentlich gewesen (olduğu gibi), birincil kaynak yöntemi, tarafsız tarih, devlet tarihi" },
    { id: "wallerstein", name: "Immanuel Wallerstein", name_tr: "Immanuel Wallerstein", years: "1930–2019", tradition: "Dünya Sistemleri Teorisi", key_concepts: "Merkez-çevre ilişkisi, kapitalist dünya sistemi, hegemonya döngüleri, yarı-çevre" },
    { id: "gibbon", name: "Edward Gibbon", name_tr: "Edward Gibbon", years: "1737–1794", tradition: "Aydınlanma Tarihçiliği", key_concepts: "Roma İmparatorluğunun gerilemesi ve çöküşü, din eleştirisi, anıtsal tarih yazımı" },
    { id: "carr", name: "E.H. Carr", name_tr: "E.H. Carr", years: "1892–1982", tradition: "Tarih Felsefesi", key_concepts: "Tarih nedir?, tarihçi ve olgular diyaloğu, ilerleme fikri, Sovyet Rusya tarihi" },
    { id: "michelet", name: "Jules Michelet", name_tr: "Jules Michelet", years: "1798–1874", tradition: "Romantik Tarihçilik", key_concepts: "Halk tarihi, Fransız Devrimi, ulusal kimlik, tarih sanatı" },
    { id: "tuchman", name: "Barbara Tuchman", name_tr: "Barbara Tuchman", years: "1912–1989", tradition: "Anlatısal Tarih", key_concepts: "Ağustos Silahları, aptallığın yürüyüşü, savaş ve diplomasi, iktidarın körlüğü" },
    { id: "galeano", name: "Eduardo Galeano", name_tr: "Eduardo Galeano", years: "1940–2015", tradition: "Latin Amerika Tarihi", key_concepts: "Latin Amerika'nın kesik damarları, sömürgecilik eleştirisi, kaynak sömürüsü, direniş tarihi" },
    { id: "sima_qian", name: "Sima Qian", name_tr: "Sima Qian", years: "M.Ö. 145–86", tradition: "Çin Tarihçiliğinin Babası", key_concepts: "Shiji (Büyük Tarihçinin Kayıtları), biyografik tarih, hanedanlık döngüleri, tarihçinin ahlaki görevi" },
    { id: "eco", name: "Umberto Eco", name_tr: "Umberto Eco", years: "1932–2016", tradition: "Göstergebilim ve Tarihsel Roman", key_concepts: "Gülün Adı, göstergebilim, Ortaçağ araştırmaları, kültürel eleştiri, açık yapıt" },
    { id: "bloch", name: "Marc Bloch", name_tr: "Marc Bloch", years: "1886–1944", tradition: "Annales Okulu, Karşılaştırmalı Tarih", key_concepts: "Feodal toplum, karşılaştırmalı tarih yöntemi, tarihçi zanaatârlığı, Fransız Direniş hareketi" }
  ];

  /* ─── State ────────────────────────────────────────────── */
  let newsItems = NEWS_ITEMS;
  let philosophers = PHILOSOPHERS_LIST;
  let psychologists = PSYCHOLOGISTS_LIST;
  let historians = HISTORIANS_LIST;
  let philosophersMap = {};
  let currentLang = "tr";
  PHILOSOPHERS_LIST.forEach(function (p) {
    philosophersMap[p.id] = p;
  });

  let psychologistsMap = {};
  PSYCHOLOGISTS_LIST.forEach(function(p) { psychologistsMap[p.id] = p; });

  let historiansMap = {};
  HISTORIANS_LIST.forEach(function(h) { historiansMap[h.id] = h; });


  /* ─── Language toggle ────────────────────────────────────── */
  (function initLangToggle() {
    var toggle = document.getElementById("lang-toggle");
    if (!toggle) return;
    toggle.addEventListener("click", function () {
      currentLang = currentLang === "tr" ? "en" : currentLang === "en" ? "zh" : "tr";
      var opts = toggle.querySelectorAll(".lang-toggle__option");
      opts.forEach(function (opt) {
        if (opt.getAttribute("data-lang") === currentLang) {
          opt.classList.add("lang-toggle__option--active");
        } else {
          opt.classList.remove("lang-toggle__option--active");
        }
      });
      document.documentElement.setAttribute("lang", currentLang === "zh" ? "zh-CN" : currentLang);
      route();
    });
  })();

  function getNewsTitle(news) {
    if (currentLang === "en" && news.title_en) return news.title_en;
    if (currentLang === "zh" && news.title_zh) return news.title_zh;
    return news.title;
  }

  function getNewsSummary(news) {
    if (currentLang === "en" && news.summary_en) return news.summary_en;
    if (currentLang === "zh" && news.summary_zh) return news.summary_zh;
    return news.summary;
  }

  /* ─── Philosopher image mapping ────────────────────────── */
  function getPhilosopherImage(id) {
    return "./assets/philosophers/" + id.replace(/_/g, "-") + ".webp";
  }

  function getPsychologistImage(id) {
    return "./assets/psychologists/" + id + ".webp";
  }

  function getHistorianImage(id) {
    return "./assets/historians/" + id + ".webp";
  }

  /* ─── Theme toggle ─────────────────────────────────────── */
  (function initTheme() {
    var toggle = document.querySelector("[data-theme-toggle]");
    var root = document.documentElement;
    var forceTheme = new URLSearchParams(window.location.search).get("theme");
    var theme = forceTheme || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
    root.setAttribute("data-theme", theme);
    updateThemeIcon(toggle, theme);

    if (toggle) {
      toggle.addEventListener("click", function () {
        theme = theme === "dark" ? "light" : "dark";
        root.setAttribute("data-theme", theme);
        toggle.setAttribute("aria-label", theme === "dark" ? t('toggle_light') : t('toggle_dark'));
        updateThemeIcon(toggle, theme);
      });
    }
  })();

  function updateThemeIcon(toggle, theme) {
    if (!toggle) return;
    if (theme === "dark") {
      toggle.innerHTML = '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/></svg>';
    } else {
      toggle.innerHTML = '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>';
    }
  }

  /* ─── Mobile menu ──────────────────────────────────────── */
  (function initMobileMenu() {
    var btn = document.getElementById("mobile-menu-btn");
    var nav = document.getElementById("main-nav");
    if (btn && nav) {
      btn.addEventListener("click", function () {
        var isOpen = nav.classList.toggle("header__nav--open");
        btn.setAttribute("aria-expanded", isOpen ? "true" : "false");
        btn.innerHTML = isOpen
          ? '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 6L6 18M6 6l12 12"/></svg>'
          : '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 12h18M3 6h18M3 18h18"/></svg>';
      });
    }
  })();

  /* ─── Header scroll effect ─────────────────────────────── */
  (function initScrollEffect() {
    var header = document.getElementById("header");
    var lastScroll = 0;
    window.addEventListener("scroll", function () {
      var currentScroll = window.scrollY;
      if (currentScroll > 20) {
        header.classList.add("header--scrolled");
      } else {
        header.classList.remove("header--scrolled");
      }
      lastScroll = currentScroll;
    }, { passive: true });
  })();

  /* ─── Interpretation fetching ──────────────────────────── */
  function fetchInterpretation(newsId, philosopherId) {
    if (!INTERPRET_API) {
      return Promise.reject(new Error("API not configured"));
    }
    return fetch(INTERPRET_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ news_id: newsId, philosopher_id: philosopherId, lang: currentLang }),
    }).then(function (r) {
      if (r.status === 429) {
        throw new Error("RATE_LIMIT");
      }
      if (!r.ok) throw new Error("API error");
      return r.json();
    });
  }

  /* ─── Format date ──────────────────────────────────────── */
  function formatDate(dateStr) {
    var months = (currentLang === "en" ? EN : currentLang === "zh" ? ZH : TR).months;
    var parts = dateStr.split("-");
    var day = parseInt(parts[2], 10);
    var month = months[parseInt(parts[1], 10) - 1];
    var year = parts[0];
    if (currentLang === "en") return month + " " + day + ", " + year;
    if (currentLang === "zh") return year + "年" + month + day + "日";
    return day + " " + month + " " + year;
  }

  /* ─── Render: Homepage ─────────────────────────────────── */
  function renderHomepage() {
    updateNav("haberler");

    var html = '<div class="page-view">';
    html += '<section class="hero container container--narrow">';
    html += '  <svg class="hero__logo-mark" width="64" height="64" viewBox="0 0 36 36" fill="none" aria-hidden="true">';
    html += '    <circle cx="18" cy="18" r="16" stroke="var(--color-primary)" stroke-width="0.8" fill="none" opacity="0.2"/>';
    html += '    <circle cx="18" cy="18" r="11.5" stroke="var(--color-primary)" stroke-width="1.2" fill="none"/>';
    html += '    <path d="M14.8 14.2c0-2.8 2.4-4.6 4.8-3.8 1.8 0.6 2.8 2.4 2.2 4.2-0.4 1.2-1.4 2-2.4 2.6-0.6 0.4-1 1-1 1.8v1" stroke="var(--color-primary)" stroke-width="1.6" stroke-linecap="round" fill="none"/>';
    html += '    <circle cx="18.4" cy="24.5" r="1" fill="var(--color-primary)"/>';
    html += '    <circle cx="28" cy="27" r="1.5" fill="var(--color-primary)" opacity="0.3"/>';
    html += '    <circle cx="31" cy="30" r="1" fill="var(--color-primary)" opacity="0.2"/>';
    html += '  </svg>';
    html += '  <h1 class="hero__title">' + t('hero_title') + '</h1>';
    html += '  <p class="hero__tagline">' + t('hero_tagline') + '</p>';
    html += '  <div class="hero__divider"></div>';
    html += '</section>';
    html += '<section class="news-feed container container--narrow">';
    html += '  <div class="news-feed__list" id="news-list">';

    newsItems.forEach(function (news) {
      html += renderNewsCard(news);
    });

    html += '  </div>';
    html += '</section>';
    html += '</div>';

    mainEl.innerHTML = html;
    attachNewsCardListeners();
    if (INTERPRET_API) {
      loadFeaturedQuotes();
      loadFeaturedPsychQuotes();
      loadFeaturedHistQuotes();
    }
  }

  /* ─── Load featured quotes for each news card (staggered) ── */
  function loadFeaturedQuotes() {
    var queue = newsItems.filter(function (n) { return n.featured_philosopher; });
    var delay = 0;
    queue.forEach(function (news) {
      var bodyEl = document.getElementById("fq-body-" + news.id);
      if (!bodyEl) return;
      /* Show skeleton while loading */
      bodyEl.innerHTML = '<div class="featured-quote__skeleton"><div class="skeleton-line"></div><div class="skeleton-line skeleton-line--short"></div></div>';
      setTimeout(function () {
        fetchInterpretation(news.id, news.featured_philosopher)
          .then(function (data) {
            bodyEl.innerHTML = '<p class="featured-quote__text">' + data.interpretation + '</p>';
          })
          .catch(function (err) {
            if (err.message === "RATE_LIMIT") {
              bodyEl.innerHTML = '<p class="featured-quote__text featured-quote__text--error">' + t('rate_limit') + '</p>';
            } else {
              /* Retry once after 3 seconds */
              setTimeout(function () {
                fetchInterpretation(news.id, news.featured_philosopher)
                  .then(function (data2) {
                    bodyEl.innerHTML = '<p class="featured-quote__text">' + data2.interpretation + '</p>';
                  })
                  .catch(function () {
                    bodyEl.innerHTML = '<p class="featured-quote__text featured-quote__text--error">' + t('load_fail') + '</p>';
                  });
              }, 3000);
            }
          });
      }, delay);
      delay += 400;
    });
  }

  /* ─── Load featured psychologist quotes for each news card (staggered) ── */
  function loadFeaturedPsychQuotes() {
    var queue = newsItems.filter(function (n) { return n.featured_psychologist; });
    var delay = 200;
    queue.forEach(function (news) {
      var bodyEl = document.getElementById("pq-body-" + news.id);
      if (!bodyEl) return;
      bodyEl.innerHTML = '<div class="featured-quote__skeleton"><div class="skeleton-line"></div><div class="skeleton-line skeleton-line--short"></div></div>';
      setTimeout(function () {
        fetchInterpretation(news.id, news.featured_psychologist)
          .then(function (data) {
            bodyEl.innerHTML = '<p class="featured-quote__text">' + data.interpretation + '</p>';
          })
          .catch(function (err) {
            if (err.message === "RATE_LIMIT") {
              bodyEl.innerHTML = '<p class="featured-quote__text featured-quote__text--error">' + t('rate_limit') + '</p>';
            } else {
              setTimeout(function () {
                fetchInterpretation(news.id, news.featured_psychologist)
                  .then(function (data2) {
                    bodyEl.innerHTML = '<p class="featured-quote__text">' + data2.interpretation + '</p>';
                  })
                  .catch(function () {
                    bodyEl.innerHTML = '<p class="featured-quote__text featured-quote__text--error">' + t('load_fail') + '</p>';
                  });
              }, 3000);
            }
          });
      }, delay);
      delay += 400;
    });
  }

  /* ─── Load featured historian quotes for each news card (staggered) ── */
  function loadFeaturedHistQuotes() {
    var queue = newsItems.filter(function (n) { return n.featured_historian; });
    var delay = 400;
    queue.forEach(function (news) {
      var bodyEl = document.getElementById("hq-body-" + news.id);
      if (!bodyEl) return;
      bodyEl.innerHTML = '<div class="featured-quote__skeleton"><div class="skeleton-line"></div><div class="skeleton-line skeleton-line--short"></div></div>';
      setTimeout(function () {
        fetchInterpretation(news.id, news.featured_historian)
          .then(function (data) {
            bodyEl.innerHTML = '<p class="featured-quote__text">' + data.interpretation + '</p>';
          })
          .catch(function (err) {
            if (err.message === "RATE_LIMIT") {
              bodyEl.innerHTML = '<p class="featured-quote__text featured-quote__text--error">' + t('rate_limit') + '</p>';
            } else {
              setTimeout(function () {
                fetchInterpretation(news.id, news.featured_historian)
                  .then(function (data2) {
                    bodyEl.innerHTML = '<p class="featured-quote__text">' + data2.interpretation + '</p>';
                  })
                  .catch(function () {
                    bodyEl.innerHTML = '<p class="featured-quote__text featured-quote__text--error">' + t('load_fail') + '</p>';
                  });
              }, 3000);
            }
          });
      }, delay);
      delay += 400;
    });
  }

  function renderNewsCard(news) {
    var featuredPid = news.featured_philosopher;
    var featuredP = featuredPid ? philosophersMap[featuredPid] : null;
    var featuredPsychId = news.featured_psychologist;
    var featuredPsych = featuredPsychId ? psychologistsMap[featuredPsychId] : null;
    var featuredHistId = news.featured_historian;
    var featuredHist = featuredHistId ? historiansMap[featuredHistId] : null;
    var isAd = news.is_ad || false;

    var shareEncoded = encodeURIComponent(getNewsTitle(news) + "\n\n" + getNewsSummary(news) + "\n\nhttps://nederdi.com/#/haber/" + news.id);

    var html = '<article class="news-card' + (isAd ? ' news-card--ad' : '') + '" data-news-id="' + news.id + '">';

    /* WhatsApp share button */
    html += '<button class="news-card__share-btn" data-share-encoded="' + shareEncoded + '" aria-label="Paylaş"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/></svg></button>';

    if (isAd) {
      html += '  <div class="news-card__ad-badge"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg> ' + t('sponsored') + '</div>';
    }
    html += '  <div class="news-card__meta">';
    html += '    <span class="news-card__category" data-cat="' + news.category + '">' + tCat(news.category) + '</span>';
    html += '    <span class="news-card__date">' + formatDate(news.date) + '</span>';
    html += '    <span class="news-card__source"><a href="' + news.source_url + '" target="_blank" rel="noopener noreferrer">' + news.source_name + '</a></span>';
    html += '  </div>';
    html += '  <h2 class="news-card__title">' + getNewsTitle(news) + '</h2>';
    html += '  <p class="news-card__summary">' + getNewsSummary(news) + '</p>';

    /* Featured philosopher quote preview */
    if (featuredP) {
      html += '  <div class="news-card__featured-quote" id="featured-' + news.id + '">';
      html += '    <div class="featured-quote__header">';
      html += '      <img class="featured-quote__img" src="' + getPhilosopherImage(featuredPid) + '" alt="' + pName(featuredP) + '" width="40" height="40">';
      html += '      <div class="featured-quote__meta">';
      html += '        <span class="featured-quote__name">' + pName(featuredP) + '</span>';
      html += '        <span class="featured-quote__label">' + t('ne_derdi') + '</span>';
      html += '      </div>';
      html += '    </div>';
      html += '    <div class="featured-quote__body" id="fq-body-' + news.id + '">';
      if (INTERPRET_API) {
        html += '      <div class="featured-quote__skeleton">';
        html += '        <div class="skeleton-line"></div>';
        html += '        <div class="skeleton-line skeleton-line--short"></div>';
        html += '      </div>';
      } else {
        html += '      <p class="featured-quote__text featured-quote__text--error">' + t('api_not_ready') + '</p>';
      }
      html += '    </div>';
      html += '  </div>';
    }

    /* Featured psychologist quote preview */
    if (featuredPsych) {
      html += '  <div class="news-card__featured-quote news-card__featured-quote--psych" id="psych-featured-' + news.id + '">';
      html += '    <div class="featured-quote__header">';
      html += '      <img class="featured-quote__img" src="' + getPsychologistImage(featuredPsychId) + '" alt="' + pName(featuredPsych) + '" width="40" height="40">';
      html += '      <div class="featured-quote__meta">';
      html += '        <span class="featured-quote__name">' + pName(featuredPsych) + '</span>';
      html += '        <span class="featured-quote__label">' + t('ne_hissederdi') + '</span>';
      html += '      </div>';
      html += '    </div>';
      html += '    <div class="featured-quote__body" id="pq-body-' + news.id + '">';
      if (INTERPRET_API) {
        html += '      <div class="featured-quote__skeleton">';
        html += '        <div class="skeleton-line"></div>';
        html += '        <div class="skeleton-line skeleton-line--short"></div>';
        html += '      </div>';
      } else {
        html += '      <p class="featured-quote__text featured-quote__text--error">' + t('api_not_ready') + '</p>';
      }
      html += '    </div>';
      html += '  </div>';
    }

    /* Featured historian quote preview */
    if (featuredHist) {
      html += '  <div class="news-card__featured-quote news-card__featured-quote--hist" id="hist-featured-' + news.id + '">';
      html += '    <div class="featured-quote__header">';
      html += '      <img class="featured-quote__img" src="' + getHistorianImage(featuredHistId) + '" alt="' + pName(featuredHist) + '" width="40" height="40">';
      html += '      <div class="featured-quote__meta">';
      html += '        <span class="featured-quote__name">' + pName(featuredHist) + '</span>';
      html += '        <span class="featured-quote__label">' + t('ne_yazardi') + '</span>';
      html += '      </div>';
      html += '    </div>';
      html += '    <div class="featured-quote__body" id="hq-body-' + news.id + '">';
      if (INTERPRET_API) {
        html += '      <div class="featured-quote__skeleton">';
        html += '        <div class="skeleton-line"></div>';
        html += '        <div class="skeleton-line skeleton-line--short"></div>';
        html += '      </div>';
      } else {
        html += '      <p class="featured-quote__text featured-quote__text--error">' + t('api_not_ready') + '</p>';
      }
      html += '    </div>';
      html += '  </div>';
    }

    html += '  <div class="news-card__divider"></div>';
    html += '  <p class="news-card__philosophers-label">' + t('ask_others') + '</p>';
    html += '  <div class="news-card__philosophers">';

    if (news.philosopher_ids) {
      var philThumbs = news.philosopher_ids.filter(function(pid){ return pid !== featuredPid; }).slice(0,7);
      philThumbs.forEach(function (pid) {
        var p = philosophersMap[pid];
        if (p) {
          html += '<button class="philosopher-thumb" data-philosopher-id="' + pid + '" data-news-id="' + news.id + '" aria-label="' + pName(p) + '">';
          html += '  <img class="philosopher-thumb__img" src="' + getPhilosopherImage(pid) + '" alt="' + pName(p) + '" width="48" height="48">';
          html += '  <span class="philosopher-thumb__name">' + pName(p) + '</span>';
          html += '</button>';
        }
      });
    }

    html += '  </div>';

    /* Psychologist thumbs */
    if (news.psychologist_ids && news.psychologist_ids.length > 0) {
      html += '  <div class="news-card__divider" style="margin-top:var(--space-4)"></div>';
      html += '  <p class="news-card__philosophers-label">' + t('ask_other_psychologists') + '</p>';
      html += '  <div class="news-card__philosophers">';
      var psyThumbs = news.psychologist_ids.filter(function(pid){ return pid !== featuredPsychId; }).slice(0,7);
      psyThumbs.forEach(function (pid) {
        var p = psychologistsMap[pid];
        if (p) {
          html += '<button class="psychologist-thumb philosopher-thumb" data-psychologist-id="' + pid + '" data-news-id="' + news.id + '" aria-label="' + pName(p) + '">';
          html += '  <img class="philosopher-thumb__img" src="' + getPsychologistImage(pid) + '" alt="' + pName(p) + '" width="48" height="48">';
          html += '  <span class="philosopher-thumb__name">' + pName(p) + '</span>';
          html += '</button>';
        }
      });
      html += '  </div>';
    }

    /* Historian thumbs */
    if (news.historian_ids && news.historian_ids.length > 0) {
      html += '  <div class="news-card__divider" style="margin-top:var(--space-4)"></div>';
      html += '  <p class="news-card__philosophers-label">' + t('ask_other_historians') + '</p>';
      html += '  <div class="news-card__philosophers">';
      var histThumbs = news.historian_ids.filter(function(hid){ return hid !== featuredHistId; }).slice(0,7);
      histThumbs.forEach(function (hid) {
        var h = historiansMap[hid];
        if (h) {
          html += '<button class="historian-thumb philosopher-thumb" data-historian-id="' + hid + '" data-news-id="' + news.id + '" aria-label="' + pName(h) + '">';
          html += '  <img class="philosopher-thumb__img" src="' + getHistorianImage(hid) + '" alt="' + pName(h) + '" width="48" height="48">';
          html += '  <span class="philosopher-thumb__name">' + pName(h) + '</span>';
          html += '</button>';
        }
      });
      html += '  </div>';
    }

    html += '</article>';
    return html;
  }

  function attachNewsCardListeners() {
    var thumbs = document.querySelectorAll(".philosopher-thumb:not(.psychologist-thumb):not(.historian-thumb)");
    thumbs.forEach(function (thumb) {
      thumb.addEventListener("click", function () {
        var philosopherId = this.getAttribute("data-philosopher-id");
        var newsId = this.getAttribute("data-news-id");
        if (philosopherId) openInterpretationModal(newsId, philosopherId);
      });
    });
    var psychThumbs = document.querySelectorAll(".psychologist-thumb");
    psychThumbs.forEach(function (thumb) {
      thumb.addEventListener("click", function () {
        var psychologistId = this.getAttribute("data-psychologist-id");
        var newsId = this.getAttribute("data-news-id");
        if (psychologistId) openPsychInterpretationModal(newsId, psychologistId);
      });
    });
    var histThumbs = document.querySelectorAll(".historian-thumb");
    histThumbs.forEach(function (thumb) {
      thumb.addEventListener("click", function () {
        var historianId = this.getAttribute("data-historian-id");
        var newsId = this.getAttribute("data-news-id");
        if (historianId) openHistInterpretationModal(newsId, historianId);
      });
    });
    /* Share buttons — mobile: whatsapp app, desktop: web.whatsapp */
    var isMobile = /Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
    var shareBtns = document.querySelectorAll(".news-card__share-btn");
    shareBtns.forEach(function (btn) {
      btn.addEventListener("click", function (e) {
        e.preventDefault();
        e.stopPropagation();
        var encoded = this.getAttribute("data-share-encoded");
        if (!encoded) return;
        if (isMobile) {
          window.location.href = "whatsapp://send?text=" + encoded;
        } else {
          window.open("https://web.whatsapp.com/send?text=" + encoded, "_blank");
        }
      });
    });
  }

  /* ─── Render: Philosophers Page ────────────────────────── */
  function renderPhilosophersPage() {
    updateNav("filozoflar");

    var html = '<div class="page-view">';
    html += '<section class="philosophers-page container">';
    html += '  <h1 class="philosophers-page__title">' + t('phil_page_title') + '</h1>';
    html += '  <p class="philosophers-page__subtitle">' + t('phil_page_subtitle') + '</p>';
    html += '  <div class="philosophers-grid">';

    philosophers.forEach(function (p) {
      html += '<button class="philosopher-card" data-philosopher-id="' + p.id + '" aria-label="' + pName(p) + '">';
      html += '  <img class="philosopher-card__img" src="' + getPhilosopherImage(p.id) + '" alt="' + pName(p) + '" width="80" height="80">';
      html += '  <h2 class="philosopher-card__name">' + pName(p) + '</h2>';
      html += '  <p class="philosopher-card__years">' + p.years + '</p>';
      html += '  <p class="philosopher-card__tradition">' + p.tradition + '</p>';
      html += '</button>';
    });

    html += '  </div>';
    html += '</section>';
    html += '</div>';

    mainEl.innerHTML = html;
    attachPhilosopherCardListeners();
  }

  function attachPhilosopherCardListeners() {
    var cards = document.querySelectorAll(".philosopher-card");
    cards.forEach(function (card) {
      card.addEventListener("click", function () {
        var pid = this.getAttribute("data-philosopher-id");
        openPhilosopherDetailModal(pid);
      });
    });
  }

  /* ─── Modal: Interpretation ────────────────────────────── */
  var interpretationModal = document.getElementById("interpretation-modal");
  var modalCloseBtn = document.getElementById("modal-close");

  function openInterpretationModal(newsId, philosopherId) {
    var p = philosophersMap[philosopherId];
    var news = newsItems.find(function (n) { return n.id === newsId; });
    if (!p || !news) return;

    document.getElementById("modal-img").src = getPhilosopherImage(philosopherId);
    document.getElementById("modal-img").alt = pName(p);
    document.getElementById("modal-philosopher-name").textContent = pName(p);
    document.getElementById("modal-years").textContent = p.years;
    document.getElementById("modal-tradition").textContent = p.tradition;
    document.getElementById("modal-news-title").textContent = getNewsTitle(news);

    var body = document.getElementById("modal-body");

    if (!INTERPRET_API) {
      body.innerHTML = '<div class="error-state">' + t('api_not_configured') + '</div>';
      interpretationModal.classList.add("modal-overlay--open");
      document.body.style.overflow = "hidden";
      return;
    }

    body.innerHTML = '<div class="modal__loading">' +
      '<div class="modal__loading-spinner"></div>' +
      '<p class="modal__loading-text">' + pName(p) + t('thinking') + '</p>' +
      '</div>';

    interpretationModal.classList.add("modal-overlay--open");
    document.body.style.overflow = "hidden";

    fetchInterpretation(newsId, philosopherId)
      .then(function (data) {
        body.innerHTML = '<div class="modal__interpretation">' + data.interpretation + '</div>';
      })
      .catch(function (err) {
        if (err.message === "RATE_LIMIT") {
          body.innerHTML = '<div class="error-state">' + t('rate_limit_modal') + '</div>';
        } else {
          body.innerHTML = '<div class="error-state">' + t('load_fail_modal') + '</div>';
        }
      });
  }

  function closeInterpretationModal() {
    interpretationModal.classList.remove("modal-overlay--open");
    document.body.style.overflow = "";
  }

  modalCloseBtn.addEventListener("click", closeInterpretationModal);
  interpretationModal.addEventListener("click", function (e) {
    if (e.target === interpretationModal) closeInterpretationModal();
  });

  /* ─── Modal: Psychologist Interpretation ──────────────── */
  function openPsychInterpretationModal(newsId, psychologistId) {
    var p = psychologistsMap[psychologistId];
    var news = newsItems.find(function (n) { return n.id === newsId; });
    if (!p || !news) return;

    document.getElementById("modal-img").src = getPsychologistImage(psychologistId);
    document.getElementById("modal-img").alt = pName(p);
    document.getElementById("modal-philosopher-name").textContent = pName(p);
    document.getElementById("modal-years").textContent = p.years;
    document.getElementById("modal-tradition").textContent = p.tradition;
    document.getElementById("modal-news-title").textContent = getNewsTitle(news);

    var body = document.getElementById("modal-body");

    if (!INTERPRET_API) {
      body.innerHTML = '<div class="error-state">' + t('api_not_configured') + '</div>';
      interpretationModal.classList.add("modal-overlay--open");
      document.body.style.overflow = "hidden";
      return;
    }

    body.innerHTML = '<div class="modal__loading">' +
      '<div class="modal__loading-spinner"></div>' +
      '<p class="modal__loading-text">' + pName(p) + t('psych_thinking') + '</p>' +
      '</div>';

    interpretationModal.classList.add("modal-overlay--open");
    document.body.style.overflow = "hidden";

    fetchInterpretation(newsId, psychologistId)
      .then(function (data) {
        body.innerHTML = '<div class="modal__interpretation">' + data.interpretation + '</div>';
      })
      .catch(function (err) {
        if (err.message === "RATE_LIMIT") {
          body.innerHTML = '<div class="error-state">' + t('rate_limit_modal') + '</div>';
        } else {
          body.innerHTML = '<div class="error-state">' + t('load_fail_modal') + '</div>';
        }
      });
  }

  /* ─── Modal: Historian Interpretation ──────────────────── */
  function openHistInterpretationModal(newsId, historianId) {
    var h = historiansMap[historianId];
    var news = newsItems.find(function (n) { return n.id === newsId; });
    if (!h || !news) return;

    document.getElementById("modal-img").src = getHistorianImage(historianId);
    document.getElementById("modal-img").alt = pName(h);
    document.getElementById("modal-philosopher-name").textContent = pName(h);
    document.getElementById("modal-years").textContent = h.years;
    document.getElementById("modal-tradition").textContent = h.tradition;
    document.getElementById("modal-news-title").textContent = getNewsTitle(news);

    var body = document.getElementById("modal-body");

    if (!INTERPRET_API) {
      body.innerHTML = '<div class="error-state">' + t('api_not_configured') + '</div>';
      interpretationModal.classList.add("modal-overlay--open");
      document.body.style.overflow = "hidden";
      return;
    }

    body.innerHTML = '<div class="modal__loading">' +
      '<div class="modal__loading-spinner"></div>' +
      '<p class="modal__loading-text">' + pName(h) + t('hist_thinking') + '</p>' +
      '</div>';

    interpretationModal.classList.add("modal-overlay--open");
    document.body.style.overflow = "hidden";

    fetchInterpretation(newsId, historianId)
      .then(function (data) {
        body.innerHTML = '<div class="modal__interpretation">' + data.interpretation + '</div>';
      })
      .catch(function (err) {
        if (err.message === "RATE_LIMIT") {
          body.innerHTML = '<div class="error-state">' + t('rate_limit_modal') + '</div>';
        } else {
          body.innerHTML = '<div class="error-state">' + t('load_fail_modal') + '</div>';
        }
      });
  }

  /* ─── Modal: Philosopher Detail ────────────────────────── */
  var philosopherModal = document.getElementById("philosopher-modal");
  var philModalCloseBtn = document.getElementById("phil-modal-close");

  function openPhilosopherDetailModal(pid) {
    var p = philosophersMap[pid];
    if (!p) return;

    document.getElementById("phil-modal-img").src = getPhilosopherImage(pid);
    document.getElementById("phil-modal-img").alt = pName(p);
    document.getElementById("phil-modal-name").textContent = pName(p);
    document.getElementById("phil-modal-years").textContent = p.years;
    document.getElementById("phil-modal-tradition").textContent = p.tradition;

    var concepts = p.key_concepts.split(", ");
    var detail = document.getElementById("phil-modal-detail");
    var html = '<p class="philosopher-detail__concepts-title">' + t('key_concepts') + '</p>';
    html += '<div class="philosopher-detail__concepts">';
    concepts.forEach(function (c) {
      html += '<span class="philosopher-detail__concept-tag">' + c.trim() + '</span>';
    });
    html += '</div>';
    html += '<p class="philosopher-detail__framework-title">' + t('framework') + '</p>';

    var framework = getFrameworkDescription(pid);
    html += '<p class="philosopher-detail__framework">' + framework + '</p>';

    detail.innerHTML = html;
    philosopherModal.classList.add("modal-overlay--open");
    document.body.style.overflow = "hidden";
  }

  function closePhilosopherDetailModal() {
    philosopherModal.classList.remove("modal-overlay--open");
    document.body.style.overflow = "";
  }

  philModalCloseBtn.addEventListener("click", closePhilosopherDetailModal);
  philosopherModal.addEventListener("click", function (e) {
    if (e.target === philosopherModal) closePhilosopherDetailModal();
  });

  /* ─── Philosopher framework descriptions (Turkish) ─────── */
  function getFrameworkDescription(pid) {
    var descriptions = {
      "nietzsche": "Güç istenci, ahlak eleştirisi, Tanrı'nın ölümü ve geleneksel değerlerin ötesinde insan büyüklüğü potansiyeli üzerinden analiz yapar. Kışkırtıcı, aforizmacı ve konforlu varsayımları sorgulayıcıdır.",
      "marx": "Diyalektik materyalizm, sınıf mücadelesi, sermaye dinamikleri, emek sömürüsü ve ekonomik yapıların toplumsal ilişkileri nasıl şekillendirdiği üzerinden analiz yapar.",
      "hegel": "Tarihin diyalektik sürecini, çelişkileri ilerlemenin motoru olarak görür. Olayları Dünya Tini'nin (Weltgeist) açılımındaki anlar olarak değerlendirir.",
      "ibn_khaldun": "Asabiyye (toplumsal dayanışma), medeniyetlerin döngüsel yükselişi ve çöküşü, göçebe dinamizmi ile kentsel çöküş arasındaki gerilim üzerinden analiz yapar.",
      "plato": "İdeal formlar ile kusurlu gerçeklik, yönetimde bilgeliğin rolü, demokrasinin tiranlığa dönüşme tehlikesi ve hakikat ile adalet arayışı üzerinden analiz yapar.",
      "aristotle": "Erdem etiği, altın orta, teleolojik düşünce ve insanın doğası gereği politik bir varlık olduğu görüşü üzerinden sistematik ve ampirik analiz yapar.",
      "kant": "Kategorik imperatif, evrensel ahlak yasası, insanlığa araç değil amaç olarak davranma ödevi ve uluslar arası kalıcı barış koşulları üzerinden analiz yapar.",
      "foucault": "İktidar-bilgi ilişkileri, disiplin mekanizmaları, gözetim, biyopolitika ve kurumların bireyleri nasıl şekillendirdiği üzerinden analiz yapar. Doğal görünenin ardındaki iktidar yapılarını sorgular.",
      "rousseau": "Doğal özgürlük ile toplumsal zincirler arasındaki gerilim, genel irade, uygarlığın bozucu etkisi ve adil bir toplumsal düzenin olasılığı üzerinden analiz yapar.",
      "hobbes": "Doğa durumu (herkesin herkesle savaşı), güçlü egemen otoritenin gerekliliği, korkudan doğan toplum sözleşmesi ve güvenliğin önceliği üzerinden analiz yapar.",
      "locke": "Doğal haklar (yaşam, özgürlük, mülkiyet), yönetilenlerin rızası, tiranlığa karşı devrim hakkı ve dini hoşgörü üzerinden analiz yapar.",
      "kierkegaard": "Bireysel seçim, kaygı, inanç sıçraması ve kalabalığın konformizmine karşı otantik varoluş üzerinden analiz yapar. Kitle toplumunun bireyselliği yok etme eğilimini eleştirir.",
      "hayek": "Kendiliğinden düzen, merkezi planlamanın ölümcül kibri, bilginin dağınık doğası ve devlet müdahalesinin tehlikeleri üzerinden analiz yapar. Piyasa süreçlerini ve bireysel özgürlüğü savunur.",
      "adam_smith": "Piyasaların görünmez eli, toplumu birbirine bağlayan ahlaki duygular, uzmanlaşma ve serbest ticaretin faydaları ve devletin uygun rolü üzerinden analiz yapar.",
      "arendt": "Kamusal alan, kötülüğün sıradanlığı, totalitarizmi mümkün kılan koşullar ve siyasi eylem ile düşünmenin önemi üzerinden analiz yapar.",
      "gramsci": "Kültürel hegemonya, aydınların iktidarı sürdürme veya sorgulamadaki rolü, sivil toplumdaki mevzi savaşı ve rızanın nasıl üretildiği üzerinden analiz yapar.",
      "confucius": "Erdemli liderlik, doğru toplumsal ilişkiler, iyilikseverlik (ren), ritüel uygunluğu (li) ve ahlaki karakter gelişimi üzerinden analiz yapar.",
      "lao_tzu": "Tao (doğal yol), wu wei (eylemsizlik/zahmetsiz eylem), karşıtların dengesi ve doğal akışı kontrol etmeye çalışmanın anlamsızlığı üzerinden analiz yapar.",
      "avicenna": "Akıl ve inanç uyumu, bilgi hiyerarşisi, ruh-beden birliği ve hem felsefi sorgulama hem de ampirik gözlem yoluyla hakikat arayışı üzerinden analiz yapar.",
      "al_farabi": "Erdemli şehir (el-medînetü'l-fâzıla), felsefenin gerçek mutluluğa ulaşmadaki rolü, bilimlerin sınıflandırılması ve bilgeliği siyasi otoriteyle birleştiren ideal yönetim üzerinden analiz yapar."
    };
    return descriptions[pid] || "";
  }

  /* ─── Psychologist framework descriptions (Turkish) ─────── */
  function getPsychFrameworkDescription(pid) {
    var descriptions = {
      "wundt": "Deneysel psikolojinin kurucusu olarak bilinçli deneyimi sistematik gözlem ve iç gözlem yöntemleriyle analiz eder. İnsan zihnini parçalarına ayırarak yapısalcı bir yaklaşımla inceler.",
      "freud": "Bilinçdışı güdüler, bastırılmış arzular, id-ego-süperego dinamikleri ve çocukluk deneyimlerinin yetişkin davranışı üzerindeki belirleyici etkisi üzerinden analiz yapar. Rüya analizi ve serbest çağrışım yöntemlerini kullanır.",
      "jung": "Kolektif bilinçdışı, arketipler, gölge benlik ve bireyleşme süreci üzerinden analiz yapar. İnsan ruhunun evrensel sembollerini ve mitolojik örüntülerini keşfeder.",
      "james": "Bilinç akışı, pragmatik gerçeklik ve radikal deneycilik üzerinden analiz yapar. İnsan deneyiminin pratik sonuçlarına ve iradenin gücüne odaklanır.",
      "maslow": "İhtiyaçlar hiyerarşisi, kendini gerçekleştirme, doruk deneyimler ve büyüme motivasyonu üzerinden analiz yapar. İnsan potansiyelinin en üst noktasına ulaşma sürecini inceler.",
      "rogers": "Koşulsuz olumlu kabul, danışan merkezli terapi, öz-kavram ve empatik anlayış üzerinden analiz yapar. Bireyin doğuştan gelen büyüme ve iyileşme kapasitesine güvenir.",
      "lacan": "Ayna evresi, Gerçek-Sembolik-İmgesel üçlüsü, Öteki'nin arzusu ve jouissance kavramları üzerinden analiz yapar. Dilin ve simgesel düzenin özneyi nasıl kurduğunu sorgular.",
      "piaget": "Bilişsel gelişim evreleri, şema, özümseme-uyum süreci ve yapılandırmacılık üzerinden analiz yapar. Çocuğun dünyayı nasıl anlamlandırdığını sistematik olarak inceler.",
      "watson": "Klasik koşullanma, uyaran-tepki ilişkisi ve çevresel belirlenimcilik üzerinden analiz yapar. Gözlenebilir davranışa odaklanarak iç yaşantıyı bilimsel inceleme dışında tutar.",
      "vygotsky": "Yakınsal gelişim alanı, iskele kurma, sosyal öğrenme ve iç konuşma kavramları üzerinden analiz yapar. Bilişsel gelişimde sosyal etkileşimin ve kültürün belirleyici rolünü vurgular.",
      "fromm": "Özgürlükten kaçış, sahip olmak-olmak ikilemi, üretken karakter ve toplumsal bilinçdışı üzerinden analiz yapar. Modern toplumun bireyi nasıl yabancılaştırdığını sorgular.",
      "skinner": "Edimsel koşullanma, pekiştirme, davranışsal mühendislik ve çevresel kontrol üzerinden analiz yapar. Davranışın sonuçları tarafından şekillendirildiğini savunur.",
      "frankl": "Logoterapi, anlam istenci, varoluşsal boşluk ve trajik iyimserlik üzerinden analiz yapar. En zorlu koşullarda bile insanın anlam bulma kapasitesini vurgular.",
      "bandura": "Öz-yeterlik, gözlemsel öğrenme, karşılıklı belirlenimcilik ve model alma üzerinden analiz yapar. İnsanların çevrelerini gözlemleyerek ve modelleyerek nasıl öğrendiğini inceler.",
      "erikson": "Sekiz psikososyal gelişim evresi, kimlik krizi, psikososyal gelişim ve üretkenlik kavramları üzerinden analiz yapar. Yaşam boyu süren kimlik oluşumu sürecini inceler.",
      "horney": "Nevrotik ihtiyaçlar, temel kaygı, idealleştirilmiş benlik ve kültürel faktörlerin nevrozdaki rolü üzerinden analiz yapar. Freud'un kadın psikolojisi görüşlerini eleştirir.",
      "adler": "Aşağılık kompleksi, üstünlük çabası, toplumsal ilgi ve doğum sırası üzerinden analiz yapar. Bireyin toplumsal bağlamını ve amaç odaklı davranışını vurgular.",
      "klein": "Paranoid-şizoid konum, depresif konum, yansıtmalı özdeşim ve oyun terapisi üzerinden analiz yapar. Erken dönem nesne ilişkilerinin ruhsal yaşamı nasıl şekillendirdiğini inceler.",
      "milgram": "Otoriteye itaat, uyma davranışı, sosyal etki ve altı derece ayrımı üzerinden analiz yapar. Sıradan insanların otorite baskısı altında nasıl itaat ettiğini deneysel olarak gösterir.",
      "zimbardo": "Stanford Hapishane Deneyi, Lucifer Etkisi, zaman perspektifi ve kahramanlık hayal gücü üzerinden analiz yapar. Durumsal faktörlerin bireyleri nasıl kötülüğe sürükleyebildiğini inceler."
    };
    return descriptions[pid] || "";
  }

  /* ─── Render: Psychologists Page ────────────────────────── */
  function renderPsychologistsPage() {
    updateNav("psikologlar");

    var html = '<div class="page-view">';
    html += '<section class="philosophers-page container">';
    html += '  <h1 class="philosophers-page__title">' + t('psych_page_title') + '</h1>';
    html += '  <p class="philosophers-page__subtitle">' + t('psych_page_subtitle') + '</p>';
    html += '  <div class="philosophers-grid">';

    PSYCHOLOGISTS_LIST.forEach(function (p) {
      html += '<button class="philosopher-card psychologist-card" data-psychologist-id="' + p.id + '" aria-label="' + pName(p) + '">';
      html += '  <img class="philosopher-card__img" src="' + getPsychologistImage(p.id) + '" alt="' + pName(p) + '" width="80" height="80">';
      html += '  <h2 class="philosopher-card__name">' + pName(p) + '</h2>';
      html += '  <p class="philosopher-card__years">' + p.years + '</p>';
      html += '  <p class="philosopher-card__tradition">' + p.tradition + '</p>';
      html += '</button>';
    });

    html += '  </div>';
    html += '</section>';
    html += '</div>';

    mainEl.innerHTML = html;
    attachPsychologistCardListeners();
  }

  function attachPsychologistCardListeners() {
    var cards = document.querySelectorAll(".psychologist-card");
    cards.forEach(function (card) {
      card.addEventListener("click", function () {
        var pid = this.getAttribute("data-psychologist-id");
        openPsychologistDetailModal(pid);
      });
    });
  }

  /* ─── Render: Historians Page ────────────────────────── */
  function renderHistoriansPage() {
    updateNav("tarihciler");

    var html = '<div class="page-view">';
    html += '<section class="philosophers-page container">';
    html += '  <h1 class="philosophers-page__title">' + t('hist_page_title') + '</h1>';
    html += '  <p class="philosophers-page__subtitle">' + t('hist_page_subtitle') + '</p>';
    html += '  <div class="philosophers-grid">';

    HISTORIANS_LIST.forEach(function (h) {
      html += '<button class="philosopher-card historian-card" data-historian-id="' + h.id + '" aria-label="' + pName(h) + '">';
      html += '  <img class="philosopher-card__img" src="' + getHistorianImage(h.id) + '" alt="' + pName(h) + '" width="80" height="80">';
      html += '  <h2 class="philosopher-card__name">' + pName(h) + '</h2>';
      html += '  <p class="philosopher-card__years">' + h.years + '</p>';
      html += '  <p class="philosopher-card__tradition">' + h.tradition + '</p>';
      html += '</button>';
    });

    html += '  </div>';
    html += '</section>';
    html += '</div>';

    mainEl.innerHTML = html;
    attachHistorianCardListeners();
  }

  function attachHistorianCardListeners() {
    var cards = document.querySelectorAll(".historian-card");
    cards.forEach(function (card) {
      card.addEventListener("click", function () {
        var hid = this.getAttribute("data-historian-id");
        openHistorianDetailModal(hid);
      });
    });
  }

  /* ─── Modal: Psychologist Detail ────────────────────────── */
  var psychologistModal = document.getElementById("psychologist-modal");
  var psychModalCloseBtn = document.getElementById("psych-modal-close");

  function openPsychologistDetailModal(pid) {
    var p = psychologistsMap[pid];
    if (!p) return;

    document.getElementById("psych-modal-img").src = getPsychologistImage(pid);
    document.getElementById("psych-modal-img").alt = pName(p);
    document.getElementById("psych-modal-name").textContent = pName(p);
    document.getElementById("psych-modal-years").textContent = p.years;
    document.getElementById("psych-modal-tradition").textContent = p.tradition;

    var concepts = p.key_concepts.split(", ");
    var detail = document.getElementById("psych-modal-detail");
    var html = '<p class="philosopher-detail__concepts-title">' + t('key_concepts') + '</p>';
    html += '<div class="philosopher-detail__concepts">';
    concepts.forEach(function (c) {
      html += '<span class="philosopher-detail__concept-tag">' + c.trim() + '</span>';
    });
    html += '</div>';
    html += '<p class="philosopher-detail__framework-title">' + t('framework') + '</p>';

    var framework = getPsychFrameworkDescription(pid);
    html += '<p class="philosopher-detail__framework">' + framework + '</p>';

    detail.innerHTML = html;
    psychologistModal.classList.add("modal-overlay--open");
    document.body.style.overflow = "hidden";
  }

  function closePsychologistDetailModal() {
    psychologistModal.classList.remove("modal-overlay--open");
    document.body.style.overflow = "";
  }

  psychModalCloseBtn.addEventListener("click", closePsychologistDetailModal);
  psychologistModal.addEventListener("click", function (e) {
    if (e.target === psychologistModal) closePsychologistDetailModal();
  });

  /* ─── Modal: Historian Detail ────────────────────────── */
  var historianModal = document.getElementById("historian-modal");
  var histModalCloseBtn = document.getElementById("hist-modal-close");

  function openHistorianDetailModal(hid) {
    var h = historiansMap[hid];
    if (!h) return;

    document.getElementById("hist-modal-img").src = getHistorianImage(hid);
    document.getElementById("hist-modal-img").alt = pName(h);
    document.getElementById("hist-modal-name").textContent = pName(h);
    document.getElementById("hist-modal-years").textContent = h.years;
    document.getElementById("hist-modal-tradition").textContent = h.tradition;

    var concepts = h.key_concepts.split(", ");
    var detail = document.getElementById("hist-modal-detail");
    var html = '<p class="philosopher-detail__concepts-title">' + t('key_concepts') + '</p>';
    html += '<div class="philosopher-detail__concepts">';
    concepts.forEach(function (c) {
      html += '<span class="philosopher-detail__concept-tag">' + c.trim() + '</span>';
    });
    html += '</div>';
    html += '<p class="philosopher-detail__framework-title">' + t('framework') + '</p>';

    var framework = getHistFrameworkDescription(hid);
    html += '<p class="philosopher-detail__framework">' + framework + '</p>';

    detail.innerHTML = html;
    historianModal.classList.add("modal-overlay--open");
    document.body.style.overflow = "hidden";
  }

  function closeHistorianDetailModal() {
    historianModal.classList.remove("modal-overlay--open");
    document.body.style.overflow = "";
  }

  histModalCloseBtn.addEventListener("click", closeHistorianDetailModal);
  historianModal.addEventListener("click", function (e) {
    if (e.target === historianModal) closeHistorianDetailModal();
  });

  /* ─── Historian framework descriptions (Turkish) ─────── */
  function getHistFrameworkDescription(hid) {
    var descriptions = {
      "herodotus": "Tarihin babası olarak farklı kültürleri karşılaştırarak, gelenek ve görenekleri kaydederek ve saha araştırmasına dayalı anlatısal bir tarih yazımı yöntemiyle olayları analiz eder.",
      "thucydides": "Güç politikası, savaş analizi ve kanıta dayalı tarih yazımı üzerinden olayları yorumlar. Devletler arası ilişkilerde realizm ve çıkar çatışmasını ön plana koyar.",

      "braudel": "Longue durée (uzun süre) yaklaşımıyla coğrafyanın tarihe etkisini, üç zamanlı tarih anlayışını ve Akdeniz dünyası perspektifini kullanarak olayları yapısal düzeyde analiz eder.",
      "hobsbawm": "Marksist tarihçilik perspektifiyle devrimler çağı, sanayi devrimi, icat edilmiş gelenekler ve sınıf mücadelesi üzerinden olayları yorumlar.",
      "inalcik": "Osmanlı ekonomik ve sosyal tarihi, tımar sistemi, devlet yapılanması ve arşiv temelli araştırma yöntemiyle olayları Osmanlı tarihçiliği perspektifinden analiz eder.",
      "sima_qian": "Çin tarihçiliğinin babası olarak biyografik tarih yöntemiyle, hanedanlık döngüleri ve tarihçinin ahlaki görevini merkeze alarak olayları büyük insanların hikâyeleri üzerinden analiz eder.",
      "eco": "Göstergebilim, Ortaçağ araştırmaları ve kültürel eleştiri perspektifinden olayları yorumlar. Semboller, anlatı yapıları ve tarihin gizli katmanlarını açığa çıkarır.",
      "bloch": "Annales Okulu'nun kurucusu olarak karşılaştırmalı tarih yöntemiyle feodal toplum yapılarını analiz eder. Tarihçinin toplumsal sorumluluğunu ve direniş ahlakını her yorumun merkezine koyar.",
      "toynbee": "Meydan okuma-yanıt teorisi, medeniyetlerin doğuşu ve çöküşü, evrensel devlet kavramı ve yaratıcı azınlık perspektifiyle olayları karşılaştırmalı medeniyet tarihi çerçevesinde analiz eder.",
      "spengler": "Batının çöküşü tezi, kültürlerin organik döngüsü, Faustçu kültür kavramı ve medeniyetlerin ömrü üzerinden olayları kültür morfolojisi perspektifinde yorumlar.",
      "zinn": "Aşağıdan tarih yaklaşımı, ezilenlerin perspektifi, sivil itaatsizlik ve halk tarihi çerçevesiyle olayları iktidarın değil halkın gözünden analiz eder.",
      "said": "Oryantalizm, Doğu-Batı ikiliği, kültürel emperyalizm ve sürgün kimliği kavramlarıyla olayları postkolonyal tarih perspektifinden yorumlar.",
      "thompson": "İngiliz işçi sınıfının oluşumu, ahlak ekonomisi, aşağıdan tarih ve sınıf bilinci kavramlarıyla olayları sosyal tarih perspektifinden analiz eder.",
      "ranke": "'Wie es eigentlich gewesen' (olduğu gibi) ilkesi, birincil kaynak yöntemi ve tarafsız tarih yazımı anlayışıyla olayları modern tarih bilimi çerçevesinde değerlendirir.",
      "wallerstein": "Merkez-çevre ilişkisi, kapitalist dünya sistemi, hegemonya döngüleri ve yarı-çevre kavramlarıyla olayları dünya sistemleri teorisi perspektifinden analiz eder.",
      "gibbon": "Roma İmparatorluğunun gerilemesi ve çöküşü üzerinden tarihsel parallellikler kurarak olayları Aydınlanma tarihçiliği perspektifinden yorumlar.",
      "carr": "'Tarih nedir?' sorusu, tarihçi ve olgular diyaloğu, ilerleme fikri çerçevesinde olayları tarih felsefesi perspektifinden analiz eder.",
      "michelet": "Halk tarihi, Fransız Devrimi mirası, ulusal kimlik ve tarih sanatı perspektifiyle olayları romantik tarihçilik çerçevesinde yorumlar.",
      "tuchman": "Ağustos Silahları, aptallığın yürüyüşü, savaş ve diplomasi ile iktidarın körlüğü kavramlarıyla olayları anlatısal tarih perspektifinden analiz eder.",
      "eco": "Kapsayıcı vs sömürücü kurumlar, ekonomik eşitsizlik, siyasi kurumların rolü ve ulusların düşüşü tezleriyle olayları kurumsal ekonomik tarih perspektifinden yorumlar.",
      "galeano": "Latin Amerika'nın kesik damarları, sömürgecilik eleştirisi, kaynak sömürüsü ve direniş tarihi perspektifiyle olayları analiz eder."
    };
    return descriptions[hid] || "";
  }

  /* ─── Navigation ───────────────────────────────────────── */
  function updateNav(active) {
    var links = document.querySelectorAll(".header__nav-link");
    links.forEach(function (link) {
      var nav_key = link.getAttribute("data-nav");
      if (nav_key === active) {
        link.classList.add("header__nav-link--active");
      } else {
        link.classList.remove("header__nav-link--active");
      }
      if (nav_key === "haberler") link.textContent = t('nav_news');
      if (nav_key === "filozoflar") link.textContent = t('nav_philosophers');
      if (nav_key === "psikologlar") link.textContent = t('nav_psychologists');
      if (nav_key === "tarihciler") link.textContent = t('nav_historians');
    });

    /* Close mobile menu */
    var nav = document.getElementById("main-nav");
    nav.classList.remove("header__nav--open");
    var btn = document.getElementById("mobile-menu-btn");
    btn.innerHTML = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 12h18M3 6h18M3 18h18"/></svg>';
  }

  /* ─── Router ───────────────────────────────────────────── */
  function route() {
    var hash = window.location.hash || "#/";
    window.scrollTo(0, 0);
    document.title = currentLang === "en" ? "Ne Derdi? \u2014 History's Great Thinkers Comment on Today" : currentLang === "zh" ? "他们会怎么说？\u2014 历史伟大思想家评论当今时事" : "Ne Derdi? \u2014 Tarihin B\u00fcy\u00fck D\u00fc\u015f\u00fcn\u00fcrleri G\u00fcn\u00fcm\u00fcz\u00fc Yorumluyor";
    if (hash === "#/filozoflar") {
      renderPhilosophersPage();
    } else if (hash === "#/psikologlar") {
      renderPsychologistsPage();
    } else if (hash === "#/tarihciler") {
      renderHistoriansPage();
    } else if (hash.indexOf("#/haber/") === 0) {
      var targetId = hash.replace("#/haber/", "");
      renderHomepage();
      setTimeout(function () {
        var el = document.querySelector('[data-news-id="' + targetId + '"]');
        if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
      }, 300);
    } else {
      renderHomepage();
    }
    var disc = document.getElementById("footer-disclaimer");
    if (disc) disc.textContent = t('disclaimer');
  }

  /* ─── Keyboard: close modals with Escape ───────────────── */
  document.addEventListener("keydown", function (e) {
    if (e.key === "Escape") {
      closeInterpretationModal();
      closePhilosopherDetailModal();
      closePsychologistDetailModal();
      closeHistorianDetailModal();
    }
  });

  /* ─── Init ─────────────────────────────────────────────── */
  window.addEventListener("hashchange", route);

  /* Try fetching fresh news from API, fallback to embedded data */
  if (NEWS_API) {
    fetch(NEWS_API)
      .then(function (r) {
        if (!r.ok) throw new Error("API error");
        return r.json();
      })
      .then(function (data) {
        if (data && data.length > 0) {
          newsItems = data;
          /* Rebuild maps in case new entries appeared */
          data.forEach(function (news) {
            if (news.philosopher_ids) {
              news.philosopher_ids.forEach(function (pid) {
                if (!philosophersMap[pid]) {
                  var found = PHILOSOPHERS_LIST.find(function (p) { return p.id === pid; });
                  if (found) philosophersMap[pid] = found;
                }
              });
            }
            if (news.historian_ids) {
              news.historian_ids.forEach(function (hid) {
                if (!historiansMap[hid]) {
                  var found = HISTORIANS_LIST.find(function (h) { return h.id === hid; });
                  if (found) historiansMap[hid] = found;
                }
              });
            }
          });
        }
        route();
      })
      .catch(function () {
        /* Use embedded fallback */
        route();
      });
  } else {
    route();
  }
})();
